services:
  - type: web
    name: moodmate
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd backend && npm install && npm run start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://moodmateuser:whatever4.@cluster0.smfxtdg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: supersecretkey123
      - key: PORT
        value: 5000
